### ISSUE TITLE
How was the data in the pickle encoded?

### ISSUE THREAD

**Issue by netsalesbg-ltd** [pecu/FinancialVision#6]
Can you give us the way you serialized the data from 
[label8_eurusd_10bar_1500_500_val200_gaf_culr.pkl](https://drive.google.com/open?id=1cCym8Re1aPDep29_cj9kUavCrYzpGV-U)

**Comment by bigmoumou** [comment]
Yes, you can now find the encoding code in [util_process.py](https://github.com/pecu/FinancialVision/blob/master/Encoding%20candlesticks%20as%20images%20for%20patterns%20classification%20using%20convolutional%20neural%20networks/utils/util_process.py). 

Use the `ts2gasf` function to encode one-dimensional time-series, 

and `get_gasf` function helps to encode a multi-dimensional array at once.
