### ISSUE TITLE
Code error trainer.py

### ISSUE THREAD

**Issue by LinuxpowerLudo** [pecu/FinancialVision#7]
Hi,

i try your code but i have some trouble in : 

Deep Reinforcement Learning for Foreign Exchange Trading/trainer.py"

AttributeError: type object 'Agent' has no attribute 'from_spec'

Can you fix it please ?

Regards
Ludo.

**Comment by pecu** [comment]
Please check your environment
[the system requirements are here](https://github.com/pecu/FinancialVision/blob/master/Deep%20Reinforcement%20Learning%20for%20Foreign%20Exchange%20Trading/requirements.txt)
